# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_k7dCLhX28DBMZW9W_f_kOVCmL4K61C
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load the model
model = joblib.load('logistic_model.pkl')

st.title("Titanic Survival Prediction")

st.markdown("Enter passenger details to predict survival:")

# Collect user input
Pclass = st.selectbox("Passenger Class (1 = 1st, 2 = 2nd, 3 = 3rd)", [1, 2, 3])
Sex_male = st.radio("Gender", ["Male", "Female"])
Age = st.slider("Age", 0, 80, 30)
SibSp = st.number_input("No. of Siblings/Spouse aboard", 0, 10, 0)
Parch = st.number_input("No. of Parents/Children aboard", 0, 10, 0)
Fare = st.number_input("Fare", 0.0, 600.0, 32.0)
Embarked_Q = st.checkbox("Embarked at Queenstown (Q)?")
Embarked_S = st.checkbox("Embarked at Southampton (S)?")

# Preprocess input
Sex_male = 1 if Sex_male == "Male" else 0
Embarked_Q = 1 if Embarked_Q else 0
Embarked_S = 1 if Embarked_S else 0

input_data = pd.DataFrame([[
    Pclass, Age, SibSp, Parch, Fare, Sex_male, Embarked_Q, Embarked_S
]], columns=['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q', 'Embarked_S'])

# Prediction
if st.button("Predict"):
    result = model.predict(input_data)
    if result[0] == 1:
        st.success(" The passenger would have survived.")
    else:
        st.error(" The passenger would not have survived.")

